### ISSUE TITLE
Width of table columns "jump"

### ISSUE THREAD

**Issue by bjarnef** [DanDiplo/UmbracoTraceLogViewer#19]
Can we set a fixed width (e.g. in percent) for each column in table, so the columns doesn't "jump" when filtering from a result set to no results. Or maybe it use flexbox?

![image](https://cloud.githubusercontent.com/assets/2919859/17588349/85072c40-5fce-11e6-8f72-a6e7f057b089.png)

![image](https://cloud.githubusercontent.com/assets/2919859/17588362/9b7115ae-5fce-11e6-9ec6-234d812d6e15.png)

I think it is just the message "No log entries where found matching your criteria." that force the first column to grow.

**Comment by DanDiplo** [comment]
OK, I'll have a look at this on next release. Thanks!

**Comment by DanDiplo** [comment]
This should now be improved in latest 2.2.7 version. Let me know if it works better for you.

**Comment by bjarnef** [comment]
Great! Do you know if UAAS update this package with new updates or only in a new created project?

**Comment by DanDiplo** [comment]
I'm afraid I don't. Probably best person to ask would be Seb - https://twitter.com/cultiv
