### ISSUE TITLE
Remove logging in console from release

### ISSUE THREAD

**Issue by bjarnef** [DanDiplo/UmbracoTraceLogViewer#20]
It seems this message is logged to console window: `Loaded DiploTraceLogEditController...`

https://github.com/DanDiplo/UmbracoTraceLogViewer/blob/98128d0a408876f0dc3eaf831e2547160a049b24/Umbraco7.1.3/App_Plugins/DiploTraceLogViewer/backoffice/diplotracelog/EditController.js#L10

**Comment by DanDiplo** [comment]
This is now fixed in the latest 2.2.7 release
