### ISSUE TITLE
Support wider variety of log file names

### ISSUE THREAD

**Issue by lucasch** [DanDiplo/UmbracoTraceLogViewer#21]
The log file discovery currently has "UmbracoTraceLog" hardcoded for the file name, and doesn't appear to support the log4net "preserveLogFileNameExtension" extension.

We're using the following for our log file name:
`<file type="log4net.Util.PatternString" value="${IISLogDrive}\inetpub\logs\logfiles\${APP_POOL_ID}\umbraco\Umbraco.txt" />`
` <rollingStyle value="Date" />`
` <preserveLogFileNameExtension value="true" />`

It's awesome that the latest version supports the above pathing, but it doesn't currently support the resultant file name structure (eg Umbraco.2016-09-16.txt).  

I've spent some time updating the LogFileService and tests in my fork of the project to support this and can create a pull request if interested!

**Comment by DanDiplo** [comment]
Yeah, it was written as an Umbraco log file viewer rather than a general log4Net viewer. But if you can submit a pull request that can fix that, and can pass all the tests, that would be great. I suspect it's an edge case, but if it can be implemented, then why not? :+1:

**Comment by lucasch** [comment]
I've submitted a pull request.  I've updated the test to add a valid and invalid pattern each:
Valid : Umbraco.{date}.txt
Invalid: Umbraco.{date}.{date}.txt

I'm using a negative lookahead to prevent that invalid match and named groups in the regex to capture the various bits in one regex match.

All tests passed on my end!

**Comment by DanDiplo** [comment]
Thanks! New version released on NuGet with your changes (and some of my own):

https://www.nuget.org/packages/DiploTraceLogViewer/
