### ISSUE TITLE
Highlight current node

### ISSUE THREAD

**Issue by bjarnef** [DanDiplo/UmbracoTraceLogViewer#24]
It would be great if the current node could be highlighted like in core using `navigationService.syncTree`, e.g. like in Analytics:

https://github.com/warrenbuckley/Analytics/blob/688a9756ef1c6eafa166dc07db81b9c60f156ae4/Analytics/App_Plugins/Analytics/backOffice/AnalyticsTree/controllers/Language.Controller.js

```
navigationService.syncTree({ tree: 'analyticsTree', path: ["-1", $routeParams.id], forceReload: false });
```

**Comment by DanDiplo** [comment]
Sounds like a good idea! I'll definitely have a look at that next time I work on it (but now I'm getting ready for the Umbraco UK festival tomorrow!). You are always welcome to make a pull, request, too :) Thanks for the feedback and the handy example.

**Comment by DanDiplo** [comment]
I've just pushed 2.3.2 live which should incorporate the highlight note functionality. Let me know if it works for you. NuGet at https://www.nuget.org/packages/DiploTraceLogViewer/
