### ISSUE TITLE
Add shadow to dialog

### ISSUE THREAD

**Issue by bjarnef** [DanDiplo/UmbracoTraceLogViewer#25]
Can you add a bit shadow to the dialog like in core?
Depending on which versions of Umbraco you support - if only 7.4+ you can use `umb-overlay` component/directive, otherwise maybe just add the classes `umb-overlay umb-overlay-right` to your panel - for version before v7.4 I think it was using the class `panel`, so you can keep this class.

**Comment by DanDiplo** [comment]
I have tried using the umb-overlay directive before, but there were a few issues I encountered:
1. It's not available in earlier v7 builds
2. It doesn't really support reloading content dynamically - I think it's designed more for pickers than displaying dynamic content.

But the idea of the drop-shadow definitely is something I'd like to add. Will look at that for next version, thanks.

**Comment by bjarnef** [comment]
@DanDiplo yes, `umb-overlay` is only available in Umbraco 7.4+ ... so what I meant to say was that you could add the classes `umb-overlay umb-overlay-right` to your panel like you change the width via jQuery - or take a part of the styles and add your own class (via JavaScript/jQuery).

So, you can make it look consistent. If you choose to re-use the classes `umb-overlay umb-overlay-right` it probably won't affect older versions of Umbraco (I think that is okay) - and then it get the new styling for Umbraco 7.4+ (and you already change the width).

**Comment by bjarnef** [comment]
So here I would add those two classes:
https://github.com/DanDiplo/UmbracoTraceLogViewer/blob/master/Umbraco7.1.3/App_Plugins/DiploTraceLogViewer/backoffice/diplotracelog/edit.html#L3

I haven't tried the following, but you might be able to re-use the markup `umb-overlay` render like `umb-overlay-drawer`, where it get a consistent look in Umbraco 7.4. and in older versions of Umbraco 7 it just ignore these classes.

**Comment by DanDiplo** [comment]
Cool, I'll give that a shot next time I'm working on it.

**Comment by bjarnef** [comment]
From something like this:

![image](https://cloud.githubusercontent.com/assets/2919859/21100479/90e6d784-c074-11e6-8f35-a041ddd4abaf.png)

To this:

![image](https://cloud.githubusercontent.com/assets/2919859/21100492/a2058cf4-c074-11e6-8440-4de82de06c95.png)

Since `umb-panel` both are used in editing area and in panel (can't remember how it original was).

But with these two additional classes and this extra styling it should work. And then I don't think you need `margin-left: -840px !important;`
```
#logdetail.umb-overlay.umb-overlay-right {
  left: auto;
}
```

**Comment by DanDiplo** [comment]
Had a play around - whilst I can just add `umb-overlay.umb-overlay-right` classes, and it works like you specify, it still has the issue (for me) that the dialogue width is narrow. I'd customised it so it was wider and responsive to screen dimensions. However, I have been able to simulate the look by adding the same drop-shadow effect. This is in 2.3.2 which has just been released.
