### ISSUE TITLE
Add support for other log files

### ISSUE THREAD

**Issue by tompipe** [DanDiplo/UmbracoTraceLogViewer#29]
It'd be useful if this were able to load a collection of other logs, such as the CourierTraceLog files.

Looks like there's currently no way to change the defautlLogFnPattern in the LogFileService, so the only filenames it will pick up are those beginning with Umbraco*

**Comment by DanDiplo** [comment]
Hi. I'm not familiar with Courier logs as I've never used it. Are the contents the same format the standard Umbraco trace logs? If so, then they could be adapted to be included. But if the format is different, then even if it picked them up it wouldn't be able to display the contents.

Have you some examples of what the file names might look like? Also, this issue covers some thoughts on making the file matching less restrictive - https://github.com/DanDiplo/UmbracoTraceLogViewer/issues/26

**Comment by tompipe** [comment]
File names appear to be CourierTraceLog.txt or CourierTraceLog.txt.2017-07-01 format

Format looks the same, [here's a log snippet](https://gist.github.com/tompipe/f3a44c36a87e6a3f29514fc4dd5128a5) which is from an umbraco cloud based project of mine.

**Comment by tompipe** [comment]
Found the courier log4net config, looks like the format is 

`%date [%thread] %-5level %logger - %message%newline`

**Comment by DanDiplo** [comment]
Thanks, Tom. I'll look to see if it's possible to include it. I may get a chance to work on it some time today or tomorrow so will update this if/when I get time.

**Comment by DanDiplo** [comment]
Tom. I've got a new version working that should read these. However, I haven't time at the moment to fully test and release (as I'm going away for a few days). But expect this to be in the new version.

**Comment by tompipe** [comment]
Awesome! Thanks!

**Comment by DanDiplo** [comment]
@tompipe I've released a beta version on NuGet that I hope you can test:

https://www.nuget.org/packages/DiploTraceLogViewer/2.4.0-beta

This new version will list all files in your \Logs\ folder and you can now browse them by date or by filename.  It should pick-up courier files.

Please let me know what you think.

**Comment by tompipe** [comment]
![You're awesome!](https://media.giphy.com/media/vCKC987OpQAco/giphy-facebook_s.jpg)

I'll try give it a test tomorrow!
