### ISSUE TITLE
Bing not included as a search provider

### ISSUE THREAD

**Issue by liamlaverty** [DanDiplo/UmbracoTraceLogViewer#33]
I've made a pull requests here, I think that should add it: https://github.com/DanDiplo/UmbracoTraceLogViewer/pull/32

**Comment by DanDiplo** [comment]
Thanks, Liam, I will review it presently and if it all looks OK I'll include it in the next release.

Currently I don't have any plans for a release as I normally like to include a few more changes than this in a release, but we'll see!

**Comment by liamlaverty** [comment]
no worries, if it makes it in eventually, that's grand. Until then I can copy/paste into Bing #h5yr

**Comment by DanDiplo** [comment]
It's been a long-time coming, I know, but this has eventually been added, as I just made a minor release!
