### ISSUE TITLE
Logfiles list should be list view instead of list in tree

### ISSUE THREAD

**Issue by nul800sebastiaan** [DanDiplo/UmbracoTraceLogViewer#6]
Just so I don't forget: something that I've been wanting to have for a long time is to have the list of log files as a list view instead of it being that long list in the tree (a new file gets created daily so after a while it gets pretty long).

**Comment by DanDiplo** [comment]
Doug mentioned the same - https://our.umbraco.org/projects/developer-tools/diplo-trace-log-viewer/diplo-trace-log-viewer/60998-Use-ListView-instead-of-tree-nodes

I just don't know how you create this in U7? Are there any examples?

As an alternative one thing I thought of was to perhaps nest the files in the tree in folders based on the month/year. That would at least keep the list more manageable. Perhaps have the latest 7 files not nested, for ease of access?

**Comment by nul800sebastiaan** [comment]
I think Doug might've inspired me during the session about the doctype editor last week!

Not sure how to do it yet, but I'm sure we can get some help from Per and Shannon. :-)

**Comment by nul800sebastiaan** [comment]
Ha! Just remembered this project: https://github.com/robertjf/umbMemberListView

So it's definitely do-able AND we have example code, what more could we want!

**Comment by DanDiplo** [comment]
There is kind-of a listview now, too, as well as tree and, well, this is ancient :)
